version: 2

# Keep this at the top to reduce noise in chatrooms when we mess up circleci setup
experimental:
  notify:
    branches:
      only:
      - master

jobs:
  build:
    docker:
    - image: circleci/node:10-browsers  # -browsers image has java but is otherwise relatively small
    steps:
    - checkout
    - run:
        name: Install Swagger Codegen
        command: |
          wget https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.4.8/swagger-codegen-cli-2.4.8.jar -O swagger-codegen-cli.jar
          printf '#!/bin/bash\nexec java -jar /usr/local/bin/swagger-codegen-cli.jar "$@"\n' > ./swagger-codegen
          sudo mv ./swagger-codegen /usr/local/bin
          sudo mv ./swagger-codegen-cli.jar /usr/local/bin
          sudo chmod +x /usr/local/bin/swagger-codegen

    - run:
        name: Install pip
        command: sudo apt install python-pip

    - run:
        name: Loading previous client repos
        command: |
          export REPO_USER_URL=https://github.com/$CIRCLE_PROJECT_USERNAME
          make load_prior_targets

    - run:
        name: Generating code
        command: |
          export REPO_USER_URL=https://github.com/$CIRCLE_PROJECT_USERNAME
          make all

    - run:
        name: Archiving targets
        command: |
          cd targets
          VERSION=$(cat openapi.json | jq -r '.info.version')
          tar cvfz api-clients-${VERSION}-${CIRCLE_SHA1:0:7}.tgz api-client-*
          mkdir /tmp/api-clients
          cp api-clients-*.tgz /tmp/api-clients

    - persist_to_workspace:
        root: targets
        paths:
        - .

    - store_artifacts:
        path: targets/html2
        destination: html

    - store_artifacts:
        path: targets/html
        destination: html-plain

    - store_artifacts:
        path: /tmp/api-clients

  test-go:
    docker:
    - image: circleci/golang
    steps:
    - checkout
    - attach_workspace:
        at: targets
    - run:  |
        mkdir -p /go/src/github.com/launchdarkly
        cp -r targets/api-client-go /go/src/github.com/launchdarkly/
    - run: |
        cd samples/go
        make

  test-javascript:
    docker:
    - image: circleci/node
    steps:
    - checkout
    - attach_workspace:
        at: targets
    - run: |
        cd samples/javascript
        sudo npm link ../../targets/api-client-javascript
        node index.js

  test-python:
    docker:
    - image: circleci/python:3.7
    steps:
    - checkout
    - attach_workspace:
        at: targets
    - run: |
        cd samples/python
        sudo pip install -e ../../targets/api-client-python
        python main.py

  test-ruby:
    docker:
    - image: circleci/ruby
    steps:
    - checkout
    - attach_workspace:
        at: targets
    - run:
        name: Install Gem
        command: |
          cd targets/api-client-ruby
          gem build launchdarkly_api.gemspec
          gem install ./launchdarkly_api*.gem
    - run: |
        cd samples/ruby
        ruby main.rb

workflows:
  version: 2
  build:
    jobs:
    - build:
        filters:
          branches:
            ignore:
            - gh-pages
          tags:
            only:
              /.*/ # Required in order to run publish job for a tag push
    - test-go:
        requires:
        - build
    - test-javascript:
        requires:
        - build
    - test-python:
        requires:
        - build
    - test-ruby:
        requires:
        - build
